# Generated by Django 3.1.1 on 2020-09-03 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 9, 46, 34, 237122, tzinfo=utc)),
        ),
    ]
