# Generated by Django 3.1.1 on 2020-09-25 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='text',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 18, 31, 15, 510610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(default='GET', max_length=10),
        ),
    ]
