# Generated by Django 3.1.1 on 2020-09-27 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20200925_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 10, 9, 38, 667531, tzinfo=utc)),
        ),
    ]
